# Generated by Django 5.0.4 on 2024-05-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='producto_default.png', upload_to='productos_img/'),
        ),
    ]
